### PR TITLE
fix: OPTIC-1608: Seeking video frame by frame sometimes produces duplicated or skipped frames visually

### LINKED ISSUE #6593: Frame Skipping Causes Label Misalignment in Video Annotation
# Description
I created a video with OpenCV at 10 FPS and labeled its first 10 frames in Label Studio. When I refresh the page and open the task, the label aligns perfectly on the first frame. However, when I advance to the second frame, the video quickly skips the second frame and displays the third frame, but still shows the bounding box intended for the second frame (see the example below).

# To reproduce:
### UI Labeling Configuration::
```html
<View>
   <Labels name="videoLabels" toName="video" allowEmpty="true">
     <Label value="Man" background="blue"/>
     <Label value="Woman" background="red"/>
     <Label value="Other" background="green"/>
   </Labels>
   
   <!-- Please specify FPS carefully, it will be used for all project videos -->
   <Video name="video" value="$video" framerate="$fps"/>
   <VideoRectangle name="box" toName="video"/>
</View>
```
## Task with Annotation
```json
{
  "id": 15,
  "data": {
    "video": "/data/upload/1/2d96aee1-20241025-145032-937345_day.mp4",
    "fps": 10
  },
  "annotations": [
    {
      "id": 4,
      "result": [
        {
          "value": {
            "framesCount": 43,
            "duration": 4.3,
            "sequence": [
              {"enabled": true, "frame": 1, "height": 1.39, "rotation": 0, "time": 0.1, "width": 3.41, "x": 51.42, "y": 50.35},
              {"enabled": true, "frame": 2, "height": 1.39, "rotation": 0, "time": 0.2, "width": 3.27, "x": 50.43, "y": 50.35},
              {"enabled": true, "frame": 3, "height": 1.56, "rotation": 0, "time": 0.3, "width": 3.41, "x": 49.57, "y": 50.17},
              {"enabled": true, "frame": 4, "height": 1.56, "rotation": 0, "time": 0.4, "width": 3.41, "x": 48.58, "y": 50.17},
              {"enabled": true, "frame": 5, "height": 1.39, "rotation": 0, "time": 0.5, "width": 3.27, "x": 47.73, "y": 50.17},
              {"enabled": true, "frame": 6, "height": 1.39, "rotation": 0, "time": 0.6, "width": 3.27, "x": 46.88, "y": 50.17},
              {"enabled": true, "frame": 7, "height": 1.56, "rotation": 0, "time": 0.7, "width": 3.27, "x": 45.88, "y": 50},
              {"enabled": true, "frame": 8, "height": 1.56, "rotation": 0, "time": 0.8, "width": 3.41, "x": 45.03, "y": 50},
              {"enabled": true, "frame": 9, "height": 1.56, "rotation": 0, "time": 0.9, "width": 3.27, "x": 44.18, "y": 50},
              {"enabled": true, "frame": 10, "height": 1.56, "rotation": 0, "time": 1, "width": 3.27, "x": 43.18, "y": 50}
            ]
          },
          "id": "xNNNVLwq5Y",
          "from_name": "box",
          "to_name": "video",
          "type": "videorectangle",
          "origin": "manual"
        }
      ],
      "created_username": "di@mail.com",
      "created_ago": "3 hours, 56 minutes",
      "completed_by": {
        "id": 1,
        "email": "di@mail.com",
        "initials": "di"
      },
      "was_cancelled": false,
      "ground_truth": false,
      "created_at": "2024-11-01T18:05:06.388864Z",
      "updated_at": "2024-11-01T18:45:51.407308Z",
      "lead_time": 2214.572,
      "task": 15,
      "project": 1
    }
  ],
  "predictions": []
}
```
# Expected Behavior:
Navigating the video back and forth, the labels should always remain aligned with the images.

# Actual Behavior

1. After refreshing the page on the first frame: The label aligns correctly with the displayed image.
image

2. When advancing to the second frame: The second frame is quickly skipped, and the third frame is displayed, but it shows the label intended for the second frame. Note that the timeline is poinintg on the 2nd frame here
image

3. When returning to the first frame: The video displays the second frame, but with the label from the first frame. From this point onward, labels are consistently one frame behind the displayed image, regardless of the selected frame. This misalignment continues if I advance further, and the actual first frame is never shown again until I refresh the page.

image

After this misalignment starts, the labels stay one frame behind the images until I refresh the page. However, after refreshing, the issue recurs as soon as I advance by one frame, following the same pattern.

The root of the problem seems to be in the video display, which skips a frame as described, while the label display remains correctly sequenced.

# Video used
https://github.com/user-attachments/assets/f58110d2-63d7-4ca3-9b56-9a3c6a511d2c

# Summary
This appears to be a bug that causes video frames and labels to become misaligned, making accurate video labeling challenging. This misalignment significantly impacts labeling precision, so addressing it would improve usability and reliability for video annotation tasks.

**Environment (please complete the following information):**
 - OS: ubuntu 22.04
 - Label Studio Version: docker 1.13.1

### PR DESCRIPTION
**Pull request by bmartel**
### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [X] Frontend

### Describe the reason for change

There were some reports of issues using Video with certain video files, specifically with regards to skipped or duplicated frames. Looking at the commonalities of these reports and investigating further the types of files that were producing known issues, the observation was that the way video was calculating frame seeking was incorrect.

There were two problems:
1. Visual display of frames is 1-based, while calculations of seeking frames is 0 based, because it is based on time.
2. The step of any given frame was calculating exactly, which does not work in browsers as browser precision is at best 2ms.

#### Reproduction
Created a Label Studio project with the following:

**Config**

```xml
<View>
   <Labels name="videoLabels" toName="video" allowEmpty="true">
     <Label value="Man" background="blue"/>
     <Label value="Woman" background="red"/>
     <Label value="Other" background="green"/>
   </Labels>
   
   <!-- Please specify FPS carefully, it will be used for all project videos -->
   <Video name="video" value="$video" framerate="24"/>
   <VideoRectangle name="box" toName="video"/>
</View>
```

**Video File**

[fps_24_frames_9999_video.webm](https://github.com/user-attachments/assets/350017b6-188c-439e-bb1b-bb42778c9f37)

#### What does this fix?
1. We properly calculate the display of frames, and the seeking of frames accordingly.
2. We round the value of a seek step to the nearest next browser precision point.

Closes #6593

#### What is the new behavior?
Seeking frame by frame now correctly works for all videos.

[Kapture 2025-02-05 at 17.16.54.webm](https://github.com/user-attachments/assets/4f70948d-35a7-4207-8379-4db170fef49f)

#### What is the current behavior?
Seeking frame by frame worked for some videos, but struggled in cases where the framerate was low or in short video clips.

[Kapture 2025-02-05 at 17.11.32.webm](https://github.com/user-attachments/assets/c374fe97-a57b-4f20-9138-feb62e14dbe9)

#### What feature flags were used to cover this change?
- `fflag_fix_front_optic_1608_improve_video_frame_seek_precision_short`

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [x] integration
- [ ] unit

### Which logical domain(s) does this change affect?
Video

### CODE REVIEW

File: web/libs/editor/src/components/VideoCanvas/VideoCanvas.tsx [hunk 1]
```diff
@@ -167,7 +171,9 @@ export const VideoCanvas = memo(
         if (!contextRef.current) return;
 
         const currentTime = videoRef.current?.currentTime ?? 0;
-        const frameNumber = Math.round(currentTime * framerate);
+        const frameNumber = isFF(FF_VIDEO_FRAME_SEEK_PRECISION)
+          ? Math.floor(currentTime * framerate) + 1
```
Comment (yyassi-heartex) [inline web/libs/editor/src/components/VideoCanvas/VideoCanvas.tsx]: this should be the same
```suggestion   
          ? Math.ceil(currentTime * framerate)
```

**Review by yyassi-heartex — APPROVED** [review]
minor suggestion, but other wise looks good.

File: web/libs/editor/src/components/VideoCanvas/VideoCanvas.tsx (hunk 1 above)
Comment (bmartel) [reply web/libs/editor/src/components/VideoCanvas/VideoCanvas.tsx]: Thinking about the overall solution and what is semantically be achieved it does make more sense. We are always looking for the **next** frame of the browser precision rounded time.

**Comment by bmartel** [comment]
/git merge develop
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/13181316168)
> Successfully merged:  create mode 100644 web/libs/frontend-test/src/helpers/LSF/Hotkeys.ts

**Review by AndrejOros — APPROVED** [review]

**Comment by mandulaj** [comment]
Hey, thanks for implementing this! I was trying to test it on our videos as well as on the above 24fps video.

I build the docker image for the app with `docker compose build`

However, it seems that the issue is still persisting. I made sure to clear the browser cache and the version displayed is 1.17.0-dev0. 

Any ideas why this might be the case?

**Comment by mandulaj** [comment]
I tried it in both Firefox and Brave browser with same behaviour

**Comment by bmartel** [comment]
> I tried it in both Firefox and Brave browser with same behaviour

> Any ideas why this might be the case?

This is Feature Flagged to allow for rollout, so to enable the change in behaviour you will need to run your local Label Studio docker compose instance with the following environment variable set:

- `fflag_fix_front_optic_1608_improve_video_frame_seek_precision_short=true`

**Comment by mandulaj** [comment]
@bmartel YES! Thats it! With the flag enabled it works flawlessly! 

If I understand correctly, the frame labels are now indexed starting at 1?

**Comment by mandulaj** [comment]
Although, there is still a small bug when pausing the video during playback. It seems that temporarily, the incorrect bounding box is displayed. But I think I will open this as a separate issue. Its probably related to the index calculation, but as part of the bounding box component. 

Thanks a lot!

**Comment by bmartel** [comment]
> @bmartel YES! Thats it! With the flag enabled it works flawlessly!
> 
> If I understand correctly, the frame labels are now indexed starting at 1?

The original intent was such that they were reflecting a 1-based index for frames, so to not disturb this it retains that behaviour. The difference now is that the seeking is done such that it takes into account the maximum precision steps that the browser inherently has with regards to the currentTime being set. This was sometimes throwing that off internally, and just not actually seeking to the time we were enforcing because it was too specific and producing "ghost" frames, where some are skipped others are duplicated.
