### PR TITLE
fix: Resolve concurrent render warnings during audio scroll/zoom (#7456)

### LINKED ISSUE #7456: Bug: Audio waveform zoom/scroll generates numerous "Concurrent render detected Error" messages
**Describe the bug**
Zooming or scrolling within an audio file's waveform (`AudioUltraView`) triggers a large number of `Concurrent render detected Error` messages in the developer console. This issue is present in recent commits of the `develop` branch.

**To Reproduce**
1. Go to an Audio Labeling task in Label Studio.
2. Load an audio file to display the waveform.
3. Open the browser's developer console.
4. Interact with the audio waveform:
    * Zoom in or out.
    * Scroll the waveform view horizontally.
5. See `Concurrent render detected Error` messages logged repeatedly in the console during these interactions.

**Expected behavior**
Zooming and scrolling the audio waveform should function smoothly without generating `Concurrent render detected Error` messages in the console.

**Screenshots**
*   Loom video demonstrating the error during zoom: https://www.loom.com/share/5188d12e20d74584b51ce475e29ec4f8
*   Loom video demonstrating the error during scroll: https://www.loom.com/share/1fac3602c11a4ba2b8b61666cfe5e08a
*   Error Message & Stack Trace:
    ```
    Concurrent render detected Error
    Concurrent render detected Error Component Stack
        at AudioUltraView (view.tsx:24:1)
        at wrappedComponent (observer.js:24:1)
        at div (<anonymous>)
        at wrappedComponent (observer.js:24:1)
        at Annotation (Annotation.js:5:1)
        at div (<anonymous>)
        at bem.ts:212:1
        at div (<anonymous>)
        at bem.ts:189:1
        at div (<anonymous>)
        at bem.ts:189:1
        at div (<anonymous>)
        at bem.ts:212:1
        at div (<anonymous>)
        at bem.ts:189:1
        at wrappedComponent (observer.js:24:1)
        at div (<anonymous>)
        at bem.ts:189:1
        at Provider (index.mjs:41:1)
        at Provider (index.mjs:41:1)
        at CollectionProvider (index.mjs:26:1)
    ```

**Environment (please complete the following information):**
 - OS: Any
 - Label Studio Version: Community Edition (specifically observed on recent commits from the `develop` branch, likely present in several prior commits as well).

**Additional context**
*   This issue was noticed after updating a local branch with recent changes from `develop`, but investigation confirms the bug exists in the `develop` branch itself (and potentially earlier commits). It wasn't introduced solely by the merge/rebase process.
*   The stack trace points to the `AudioUltraView` component and its MobX `observer` wrapper, suggesting a potential issue with how state updates are triggering re-renders during rapid interactions like zoom/scroll within the core codebase.

### PR DESCRIPTION
**Pull request by cloudmark**
**Fix: Reduce concurrent renders during audio waveform scroll and zoom**

Closes #7456

### Reason for change:

**Problem:**
Interacting with the audio waveform (specifically scrolling or zooming) in `AudioUltraView` frequently triggered a large number of "Concurrent render detected" errors or warnings in the developer console, as reported in issue #7456. This indicated overlapping attempts to execute the `Visualizer.draw()` method during these common interactions.

**Root Cause:**
The primary source of the high volume of warnings during scroll/zoom stemmed from these interactions inadvertently causing `Visualizer.draw()` to be called twice in rapid succession:
1.  An **explicit call** originated from the `wheel` event handler logic within `setScrollLeft` or `setZoom`.
2.  An **implicit call** occurred because the `wheel` handler logic modified the DOM element's `scrollLeft` property, which triggered the browser's native `scroll` event listener, and that listener *also* called `draw()` (via `_setScrollLeft`).

This double `draw()` call caused the internal `this.drawing` flag check within `draw()` to fail frequently, leading to the concurrent render warning/error spam during scroll and zoom.

**Solution:**
This PR implements minimal changes to eliminate the redundant `draw()` calls specifically triggered by scroll and zoom, ensuring `draw()` is only called once via the native `scroll` event listener pathway for these interactions:

1.  **Scroll Fix:** Modified `Visualizer.setScrollLeft` so it *only* updates the DOM element's `scrollLeft`. The redundant internal call (`this._setScrollLeft`) that triggered the first `draw()` was removed.
2.  **Zoom Fix:** Modified `Visualizer.setZoom` to remove its explicit call to `this.draw()`. `setZoom` still updates the DOM `scrollLeft` indirectly, allowing the native `scroll` event listener (via `_setScrollLeft`) to handle the single necessary state update and `draw()` call. The call to `this.wf.invoke("zoom", ...)` was also ensured to be correctly placed within `setZoom`.

### Screenshots:

This change primarily fixes console errors/warnings and does not introduce direct visual UI changes.

*   Original issue (Zoom): https://www.loom.com/share/5188d12e20d74584b51ce475e29ec4f8
*   Original issue (Scroll): https://www.loom.com/share/1fac3602c11a4ba2b8b61666cfe5e08a
*   **After Fix:** Console during scroll/zoom shows significantly fewer warnings: https://www.loom.com/share/73049c2edc5d40a290d930217f65955b

### Rollout strategy:

Direct merge to the target branch (e.g., `develop`). This is a bug fix reducing console noise and improving event handling logic for existing functionality.

### Testing:

Verified manually:
1.  Loaded an audio labeling task.
2.  Opened the browser developer console.
3.  Performed repeated horizontal scrolling of the waveform via mouse wheel/trackpad.
4.  Performed repeated zooming in and out of the waveform via Ctrl/Cmd + mouse wheel.
5.  Confirmed that the high volume of "Concurrent render detected" warnings/errors previously seen during scroll and zoom no longer appears. (See "After Fix" Loom video).
6.  Confirmed that scrolling and zooming visually function as expected.

### Risks:

Low risk. This change simplifies the event handling flow for scroll and zoom by removing redundant operations. Performance might slightly improve due to avoiding unnecessary `draw` calls. No known security implications.

### Reviewer notes:

*   Please focus on the changes in `Visualizer.ts` methods: `setScrollLeft` and `setZoom`.
*   The core fix eliminates the double `draw()` calls specific to scroll/zoom interactions.
*   **Note:** While this PR fixes the *majority* of the warnings related to scroll/zoom, occasional "Concurrent render detected" warnings might still appear. These likely originate from other event handlers calling `draw()` in quick succession (e.g., playback updates, or potentially the pathway involving label visibility updates: `updateLabelVisibility` -> `regions.redraw` -> `Visualizer.draw`) which might still overlap with the async part (`setTimeout`) of a previous `draw()` call. Further optimization/throttling could be explored separately if needed, but this PR addresses the primary spam reported in #7456.

### General notes:

N/A
```

### CODE REVIEW

File: web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts [hunk 1]
```diff
@@ -228,7 +231,7 @@ export class Visualizer extends Events<VisualizerEvents> {
   draw(dry = false, forceDraw = false) {
     if (this.isDestroyed) return;
     if (this.drawing && !forceDraw) return warn("Concurrent render detected");
-
+
```
Comment (bmartel) [inline web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts]:
```suggestion

```

File: web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts [hunk 2]
```diff
@@ -188,17 +188,20 @@ export class Visualizer extends Events<VisualizerEvents> {
     this.getSamplesPerPx();
     this.updateScrollFiller();
 
+    // Notify external listeners about zoom change
     this.wf.invoke("zoom", [this.zoom]);
-    this.draw();
+    // Remove explicit draw call - _setScrollLeft handles it.
+    // this.draw();
```
Comment (bmartel) [inline web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts]:
```suggestion
```

File: web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts [hunk 3]
```diff
@@ -188,17 +188,20 @@ export class Visualizer extends Events<VisualizerEvents> {
     this.getSamplesPerPx();
     this.updateScrollFiller();
 
+    // Notify external listeners about zoom change
     this.wf.invoke("zoom", [this.zoom]);
-    this.draw();
+    // Remove explicit draw call - _setScrollLeft handles it.
```
Comment (bmartel) [inline web/libs/editor/src/lib/AudioUltra/Visual/Visualizer.ts]:
```suggestion
    // _setScrollLeft handles the draw call.
```

**Comment by bmartel** [comment]
@cloudmark Locally on this branch I am seeing difficulties in zooming not working correctly, the changes did remove a large portion of the warnings but in doing so effectively made functionality overall unstable. Are you able to reproduce any issues on your end?

[Kapture 2025-05-01 at 12.59.32.webm](https://github.com/user-attachments/assets/57311351-1258-471a-ae88-996cb1a910b7)

**Comment by cloudmark** [comment]
Will check. On mine it was stable.

**Comment by cloudmark** [comment]
Is scroll working smoothly on yours? We could add the call to draw on the
zoom - the massive amount of logs come from the scroll

**Comment by bmartel** [comment]
Scrolling works fine, it is just the zooming is broken and does not render any change. I have to click in the audio viewport or do any action that would effectively trigger a redraw. The other aspect which I had noticed was broken is the Audio controls are no longer reflecting the correct values for zoom either, and I believe based on the changes here it would be the same for all functions within the audio settings dropdown.

**Comment by cloudmark** [comment]
Reverted the zoom part, will find another fix after the spectrogram.

File: web/libs/editor/src/lib/AudioUltra/react/index.ts [hunk 4]
```diff
@@ -123,49 +123,65 @@ export const useWaveform = (
...
+
+      const isWfPlaying = waveform.current.playing ?? false;
+      if (playing !== isWfPlaying) {
+        if (playing) {
+          waveform.current.play();
+        } else {
+          waveform.current.pause();
+        }
+      }
+    });
```
Comment (bmartel) [inline web/libs/editor/src/lib/AudioUltra/react/index.ts:137]: Is this part necessary?

Comment (cloudmark) [reply web/libs/editor/src/lib/AudioUltra/react/index.ts:137]: Good question! Yes, this check helps handle the timing differences with React 18's deferred effect scheduling (and our use of rAF).
For example, on a rapid Play/Pause, the cleanup might cancel the pending play() action. This check then prevents us from sending a redundant pause() command if the waveform is already paused when the effect callback actually runs. It just keeps the synchronization robust.

Comment (bmartel) [reply web/libs/editor/src/lib/AudioUltra/react/index.ts:137]: Thanks for the explanation that makes sense!

**Review by makseq — APPROVED** [review]

**Review by bmartel — APPROVED** [review]

**Comment by bmartel** [comment]
/fm sync
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/14800730739)

**Comment by makseq** [comment]
Force merged, because yarn tests is blinking and it's not related to the changes in this PR. 
@bmartel is aware of it.
